# Перемножение матриц
Напишите две функции, каждая из которых перемножает две квадратные матрицы: одна без использования встроенных функций numpy, а другая --- с помощью numpy. На вход первой задаче подаются списки размера size по size элементов в каждом. На вход второй задаче подаются объекты типа np.ndarray --- квадратные матрицы одинакового размера. 

Первая функция должна возвращать список списков, а вторая -- np.array.

In [32]:
import numpy as np

def list_mult(first, second):
    n = len(first)
    return [first[i] * second[i] for i in range(n)]

def no_numpy_mult(first, second):
    """
    param first: list of "size" lists, each contains "size" floats
    param second: list of "size" lists, each contains "size" floats
    """

    #YOUR CODE: please do not use numpy
    n = len(second)
    stolb = [[x[i] for x in second ] for i in range(n)]
    result = [[sum(list_mult(first[i], stolb[j])) for j in range(n)] for i in range(n) ]#YOUR CODE: create list of lists, not np.array
    return result

def numpy_mult(first, second):
    """
    param first: np.array[size, size]
    param second: np.array[size, size]
    """

    #YOUR CODE: please use numpy

    result = first @ second#YOUR CODE: create np.array
    return result

Вам подаются на вход два вектора a и b в трехмерном пространстве. Реализуйте их скалярное произведение с помощью numpy и без. 

In [103]:
from math import sqrt
v3 = [1,1,1]
v3sq = [i ** 2 for i in v3]
coss = sqrt(sum(v3sq))
coss

1.7320508075688772

In [130]:
from math import sqrt
import numpy as np
def d(v):
    vsq = [i ** 2 for i in v]
    return sqrt(sum(vsq))

def no_numpy_scalar(v1, v2):
    #param v1, v2: lists of 3 ints
    #YOUR CODE: please do not use numpy

    n = len(v1)
    v3 = [v1[i] - v2[i] for i in range(n)]
    d1 = d(v1) * 1.0
    d2 = d(v2) * 1.0
    d3 = d(v3) * 1.0 
    coss = (d1**2 + d2**2 - d3**2)/(2*d1*d2)
    return d1 * d2 * coss

def numpy_scalar (v1, v2):
    #param v1, v2: np.arrays[3]
    #YOUR CODE

    result = np.dot(v1,v2)#YOUR CODE
    return result

In [131]:
a = [1,1,1]
b = [2,2,2]

In [132]:
npa = np.array(a)
npb = np.array(b)

In [133]:
no_numpy_scalar(a, b)

5.999999999999999

In [134]:
numpy_scalar(npa, npb)

6

In [136]:
%time product_1 = no_numpy_scalar(a,b)
%time product_2 = numpy_scalar(npa,npb)

# проверим корректность:
assert np.allclose(product_1, product_2)

Wall time: 997 µs
Wall time: 0 ns


In [139]:
assert np.allclose(product_1, product_2)

In [128]:
d(a)

1.7320508075688772

In [129]:
sqrt(3)

1.7320508075688772

# Напишите функцию, которая находит сумму четных элементов на главной диагонали квадратной матрицы (именно чётных элементов, а не элементов на чётных позициях!). Если чётных элементов нет, то вывести 0. Используйте библиотеку numpy.

In [94]:
import numpy as np #не стирать!        

def diag_2k(a):
    #param a: np.array[size, size]
    #YOUR CODE
    n = a.shape[1]
    o = np.eye(n)
    result = o*a#YOUR CODE
    return np.sum(result[result % 2 == 0])

In [95]:
x = np.array([[1,2,4],[3,1,4],[1,1,6]])

In [96]:
x

array([[1, 2, 4],
       [3, 1, 4],
       [1, 1, 6]])

In [97]:
x.shape[1]

3

In [98]:
diag_2k(x)

6.0

In [99]:
a = np.array([1,1,1])
b = np.array([2,2,2])

In [100]:
np.dot(a,b)

6

На вход дан двумерный массив XX. Напишите функцию, которая для каждой строчки x = (x_1, x_2, \ldots, x_n)x=(x 
1
​
 ,x 
2
​
 ,…,x 
n
​
 ) массива XX строит строчку s = (s_1, s_2, \ldots, s_n)s=(s 
1
​
 ,s 
2
​
 ,…,s 
n
​
 ), где s_k=x_1+...+x_ks 
k
​
 =x 
1
​
 +...+x 
k
​
 , а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и XX.

In [2]:
import numpy as np

In [18]:
x = np.array([[1,1,1],[1,1,1]])

In [20]:
y = np.append([np.cumsum(x)], [11,32])
y

array([ 1,  2,  3,  4,  5,  6, 11, 32])

In [33]:
y = y.reshape(2,4)
y

array([[ 1,  2,  3,  4],
       [ 5,  6, 11, 32]])

In [31]:
q = np.append(np.array([y,y]), y) 
q.shape = (3, 8)
q

array([[ 1,  2,  3,  4,  5,  6, 11, 32],
       [ 1,  2,  3,  4,  5,  6, 11, 32],
       [ 1,  2,  3,  4,  5,  6, 11, 32]])

In [17]:
y.shape((2,))

TypeError: 'tuple' object is not callable

In [44]:
y

array([[ 1,  2,  3,  4],
       [ 5,  6, 11, 32]])

In [49]:

import numpy as np

def cumsum(A):
    return A.cumsum(1)

In [50]:
cumsum(y)

array([[ 1,  3,  6, 10],
       [ 5, 11, 22, 54]], dtype=int32)

Задан двумерный массив XX. Для каждой строчки массива XX необходимо сделать следующее преобразование.

Пусть дана строчка xx. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число aa (значение по умолчанию a = 1a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив xx с преобразованным xx и вернуть на выход функции (естественно, выход должен быть numpy-массивом).

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива XX. Массив XX при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
x = [[100, 200, 300, 400, 500100,200,300,400,500]] -> [[100, a, 300, a, 500100,a,300,a,500]] -> [[500^3, a, 300^3, a, 100^3500 
3
 ,a,300 
3
 ,a,100 
3
 ]] -> склеиваем -> [[100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3100,200,300,400,500,500 
3
 ,a,300 
3
 ,a,100 
3
 ]]

In [79]:
v=np.array([100,200,300,400,500])
v

array([100, 200, 300, 400, 500])

In [80]:
v[::2] **= 3

In [81]:
v

array([  1000000,       200,  27000000,       400, 125000000])

In [66]:
np.arange(1,2)

array([1])

In [82]:
v[1::2] = 1

In [83]:
v

array([  1000000,         1,  27000000,         1, 125000000])

In [85]:
v = v[::-1]

In [190]:
import numpy as np

def transform(X, a=1):
    """
    param X: np.array[batch_size, n]
    """
    n = X.shape[0]
    m = X.shape[1]
    XC = X.copy()
    XC[:, 1::2] = a
    XC[:, ::2]**=3
    XC = XC[:, ::-1]
    XC = np.append(X, XC, axis=1)
    #YOUR CODE
    return XC#.reshape((n, m*2))#YOUR CODE

In [195]:
X=np.array([[100,200,300,400,500],[1,2,3,4,5]])
X1 = np.array( [[1,2,3,4,5],[1,2,3,4,5]])
X2 = np.array( [[1,2,3,4,5]])
v=np.array([100,200,300,400,500])
tr(v, 1)

array([125000000,         1,  27000000,         1,   1000000,       100,
             200,       300,       400,       500])

In [196]:
XC = X.copy
XC

<function ndarray.copy>

In [197]:
print(transform(X, 1))


[[125000000         1  27000000         1   1000000       100       200
        300       400       500]
 [      125         1        27         1         1         1         2
          3         4         5]]


In [198]:
print(transform(X1, 1))

[[125   1  27   1   1   1   2   3   4   5]
 [125   1  27   1   1   1   2   3   4   5]]


In [199]:
print(transform(X2,1))

[[125   1  27   1   1   1   2   3   4   5]]


In [2]:
import numpy as np

In [ ]:
np.

# С помощью numpy написать функцию для кодирования массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух numpy-векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array([1, 2, 3, 1, 5, 2, 3]), np.array([1, 2, 2, 2, 2, 1, 2]))

In [ ]:
import numpy as np

def encode(a):
    #YOUR CODE
    np.arrray(a[1:])
    result = #YOUR CODE
    return result

In [ ]:
np.